
server:
  port: 8500

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/java
    username: root
    password: TranMinhVuong@10052000
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        use_sql_comments: true
        format_sql: true

mybatis:
  config-location: classpath:/mybatis/mybatis-config.xml
  mapper-locations: classpath:/mybatis/mapper/*Mapper.xml
  type-aliases-package: app.command.api.data.entity.*

logging:
  file:
    name: src/main/resources/script/prod_log.log
  logback:
    rollingpolicy:
      clean-history-on-start: true