server:
  port: 8761

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

logging:
  file:
    name: src/main/resources/script/prod_log.log