
server:
  port: 8080
  error:
    whitelabel:
      enabled: false

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  file:
    name: src/main/resources/script/prod_log.log
  logback:
    rollingpolicy:
      clean-history-on-start: true