
server:
  servlet:
    context-path: /

spring:
  application:
    name: API-GATEWAY
  profiles:
    active:
      - dev
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin, RETAIN_UNIQUE
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowed-origins: "/*"
            allowed-headers: "*"
            exposed-headers: "*"
            allow-credentials: true
            allowed-methods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTIONS
      routes:
        - id: COURSE-SERVICE
          uri: lb://COURSE-SERVICE
          predicates:
            - Path=/course-service/**
        - id: PAYMENT-SERVICE
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/payment-service/**
        - id: PRODUCT-SERVICE
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/product-service/**
        - id: SHIPPING-SERVICE
          uri: lb://SHIPPING-SERVICE
          predicates:
            - Path=/shipping-service/**
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/**
        - id: FAVOURITE-SERVICE
          uri: lb://FAVOURITE-SERVICE
          predicates:
            - Path=/favourite-service/**
        - id: PROXY-CLIENT
          uri: lb://PROXY-CLIENT
          predicates:
            - Path=/app/**